### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'cuda_device'

### ISSUE THREAD

**Issue by sheenG** [easonnie/combine-FEVER-NSMN#1]
**When i run auto_pipeline.py, there seems to be an error resulted by allennlp, output is as below:**

` Traceback (most recent call last):
    File "src/pipeline/auto_pipeline.py", line 638, in <module>
      steps=default_steps)
    File "src/pipeline/auto_pipeline.py", line 442, in pipeline
      load_from_dict=False)
    File "/home/LAB/gengxin/fever/src/nli/mesim_wn_simi_v1_2.py", line 2222, in pipeline_nli_run
      eval_iter = biterator(dev_instances, shuffle=False, num_epochs=1, cuda_device=device_num)`
**in allennlp documentation, there is no cuda_device argument among those interface related to iterator, so I'm confused about it.
when i change the last line(delete cuda_device = device_num), new error occurs:**
`Traceback (most recent call last):
  File "src/pipeline/auto_pipeline.py", line 638, in <module>
    steps=default_steps)
  File "src/pipeline/auto_pipeline.py", line 442, in pipeline
    load_from_dict=False)
  File "/home/LAB/gengxin/fever/src/nli/mesim_wn_simi_v1_2.py", line 2225, in pipeline_nli_run
    with_probs=with_probs)
  File "/home/LAB/gengxin/fever/src/nli/mesim_wn_simi_v1_2.py", line 399, in hidden_eval
    out = model(batch)
  File "/home/LAB/gengxin/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/LAB/gengxin/fever/src/nli/mesim_wn_simi_v1_2.py", line 183, in forward
    s1_tokens, s1_elmo_chars, s1_wn_f_vector)
  File "/home/LAB/gengxin/fever/src/nli/mesim_wn_simi_v1_2.py", line 163, in raw_input_to_esim_input
    s1_glove_embd = self.glove_embd_layer(s_tokens)
  File "/home/LAB/gengxin/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/LAB/gengxin/anaconda3/envs/py36/lib/python3.6/site-packages/allennlp/modules/token_embedders/embedding.py", line 134, in forward
    sparse=self.sparse)
  File "/home/LAB/gengxin/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 1110, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of type torch.cuda.LongTensor but found type torch.LongTensor for argument #3 'index' `
**Actually, I checked torch.cuda.device and result is "0" means my gpu 0 is available.
So I wonder if I should transfer data to gpu mannually.**

**Comment by easonnie** [comment]
Sorry for the late reply. This problem is due to the version incompatibility. 
Please try to use the same versions in the requirement.
```
pytorch 0.4.1
allennlp 0.7.1
```
Or, you can transfer data to GPU manually.

**Comment by sheenG** [comment]
Sir, I checked the version and the error occurs again. So I wrote several lines to test the API:
```
from allennlp.data.iterators import BasicIterator
biterator = BasicIterator(batch_size = 16)
dataset = [{'a': 1}]
eval_iter = biterator(dataset, shuffle=False, num_epochs=1, cuda_device=0)
```
and the output is : 
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    eval_iter = biterator(dataset, shuffle=False, num_epochs=1, cuda_device=0)
TypeError: __call__() got an unexpected keyword argument 'cuda_device'
```
And I found that there is no parameter 'cuda_device' in this API in allennlp 0.7.1, you can see this page:
[allennlp_data_iterator_page](https://github.com/allenai/allennlp/blob/v0.7.1/allennlp/data/iterators/data_iterator.py)
As follows:
```
def __call__(self,instances: Iterable[Instance],
                 num_epochs: int = None,
                 shuffle: bool = True) -> Iterator[TensorDict]:
```
I guess there are some mistakes.

**Comment by drfeversharedtask** [comment]
This issue hasn't been resolved yet. I have the same issue and I followed the guidelines that were provided for solving it. I ran the code multiple times and I keep having the same problem. 

Traceback (most recent call last):
  File "./src/pipeline/auto_pipeline.py", line 633, in <module>
    steps=default_steps)
  File "./src/pipeline/auto_pipeline.py", line 437, in pipeline
    load_from_dict=False)
  File "/combine-FEVER-NSMN/src/nli/mesim_wn_simi_v1_2.py", line 2218, in pipeline_nli_run
    eval_iter = biterator(dev_instances, shuffle=False, num_epochs=1, cuda_device=device_num)
TypeError: __call__() got an unexpected keyword argument 'cuda_device'
[INFO/MainProcess] process shutting down

**Comment by sheenG** [comment]
Hello, I've solved that and code went through.
original code:
```
eval_iter = biterator(dev_instances, shuffle=False, num_epochs=1, cuda_device=device_num)
complete_upstream_dev_data = hidden_eval(model, eval_iter, complete_upstream_dev_data,
                                             with_logits=with_logits,
                                             with_probs=with_probs)

```
the usage of parameter 'cuda_device' is feasible in lower version of allennlp, but in allenlp 0.7.1, this parameter is deleted(comments from joelgrus in this issue [allennlp issue](https://github.com/allenai/allennlp/issues/2539)). So you should delete 'cuda_device=device_num'.

Cause cuda_device parameter is deleted, you need to move data to device(GPU) manually.
Jump into function 'hidden_eval'.
original code:
```
for batch_idx, batch in enumerate(tqdm(data_iter)):
            out = model(batch)
            y_id_list.extend(list(batch['pid']))
```
modified as follows:
```
for batch_idx, batch in enumerate(tqdm(data_iter)):
            out = model(move_to_device(batch, cuda_device=0))
            #out = model(batch)
            y_id_list.extend(list(batch['pid']))
```
the function 'move_to_device' is imported like:
`from allennlp.nn.util import move_to_device`
and the code will go through

**Comment by easonnie** [comment]
@sheenG Thanks for the comments. I made some changes on the code and now it should go through correctly.
