### ISSUE TITLE
repeat issue -- Exception happened while reload tokenizer dictionary

### ISSUE THREAD

**Issue by djmendez** [easonnie/combine-FEVER-NSMN#7]
Any help greatly appreciated - Previous poster said issue resolved with more RAM? 16GB RAM - should be enough? Thanks

/home/djmendez/FeverPC/venv/bin/python /home/djmendez/FeverPC/venv/combine-FEVER-NSMN/src/pipeline/prepare_data.py tokenization
Start tokenizing dev and training set.
/home/djmendez/FeverPC/venv/combine-FEVER-NSMN/dep_packages/stanford-corenlp-full-2017-06-09/*
Traceback (most recent call last):
  File "/home/djmendez/FeverPC/venv/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/home/djmendez/FeverPC/venv/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 509, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/djmendez/FeverPC/venv/combine-FEVER-NSMN/src/pipeline/prepare_data.py", line 26, in <module>
    fire.Fire()
  File "/home/djmendez/FeverPC/venv/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/djmendez/FeverPC/venv/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/djmendez/FeverPC/venv/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/djmendez/FeverPC/venv/combine-FEVER-NSMN/src/pipeline/prepare_data.py", line 10, in tokenization
    tokenized_claim(config.FEVER_DEV_JSONL, config.T_FEVER_DEV_JSONL)
  File "/home/djmendez/FeverPC/venv/combine-FEVER-NSMN/src/utils/tokenize_fever.py", line 36, in tokenized_claim
    tok = CoreNLPTokenizer(annotators=['pos', 'lemma'])
  File "/home/djmendez/FeverPC/venv/combine-FEVER-NSMN/dep_packages/DrQA/drqa_yixin/tokenizers/corenlp_tokenizer.py", line 33, in __init__
    self._launch()
  File "/home/djmendez/FeverPC/venv/combine-FEVER-NSMN/dep_packages/DrQA/drqa_yixin/tokenizers/corenlp_tokenizer.py", line 61, in _launch
    self.corenlp.expect_exact('NLP>', searchwindowsize=100)
  File "/home/djmendez/FeverPC/venv/lib/python3.6/site-packages/pexpect/spawnbase.py", line 418, in expect_exact
    return exp.expect_loop(timeout)
  File "/home/djmendez/FeverPC/venv/lib/python3.6/site-packages/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/home/djmendez/FeverPC/venv/lib/python3.6/site-packages/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f9388526208>
command: /bin/bash
args: ['/bin/bash']
buffer (last 100 chars): b'l openjdk-8-jre-headless \r\n\r\ndjmendez@djmendez-OMEN:~/FeverPC/venv/combine-FEVER-NSMN/src/pipeline$ '
before (last 100 chars): b'l openjdk-8-jre-headless \r\n\r\ndjmendez@djmendez-OMEN:~/FeverPC/venv/combine-FEVER-NSMN/src/pipeline$ '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 3732
child_fd: 5
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 100000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: b'NLP>'

Process finished with exit code 1

**Comment by djmendez** [comment]
Ooops nvm
